name: Deploy Angular SPA to GitHub Pages

on:
  push:
    branches:
      - master
      - old
  pull_request:
    branches:
      - old

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js 24.13.0
        uses: actions/setup-node@v1
        with:
          node-version: '24.13.0'

      - name: Build Master 🔨
        if: github.ref == 'refs/heads/master'
        run: |
          npm install -g @angular/cli@21
          npm install
          npm run build -- --configuration production --base-href=""

      - name: Build Old 🔨
        if: github.ref == 'refs/heads/old'
        run: |
          npm install -g @angular/cli@10 --legacy-peer-deps
          npm install --legacy-peer-deps
          npm run build -- --configuration production --base-href="/OPIS-Manager/old/"

      - name: Deploy Master to / 🚀
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/opis-manager/browser/
          clean: false

      - name: Deploy Old to old/ 🚀
        if: github.ref == 'refs/heads/old'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/opis-manager
          target-folder: old
          clean: false
